Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DapperTuts.Models
{
    public class Book
    {
        public int Id { get; set; }

        public string BookName { get; set; }

        public string AuthorName { get; set; }

        public string ISBN { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace DapperTuts.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ViewModels/OperationVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DapperTuts.Models.ViewModels
{
    public class OperationVM
    {
        public string Operation { get; set; }
        public Book Book { get; set; }
    }
}

Controllers/BulkCrudController.cs
using DapperTuts.Models;
using DapperTuts.Models.ViewModels;
using DapperTuts.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace DapperTuts.Controllers
{
    public class BulkCrudController : Controller
    {
        private readonly IDapperService _dapperService;

        private const string INSERT = "INSERT";
        private const string UPDATE = "UPDATE";
        private const string DELETE = "DELETE";

        public BulkCrudController(IDapperService dapperService)
        {
            _dapperService = dapperService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dapperService.GetAll());
        }

        [HttpGet]
        public async Task<IActionResult> GetCurrentIdent()
        {
            try
            {
                int currentId = await _dapperService.GetCurrentIdent();

                return Json(new
                {
                    currentId = currentId
                });
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> SaveDatabaseBulk(List<Book> obj)
        {
            bool res = await _dapperService.BullkCrudUsingSP(obj);

            return res ? Ok() : BadRequest();
        }

        public async Task<IActionResult> SaveDatabase(List<OperationVM> obj)
        {
            bool result = false;
            try
            {
                List<Book> insertRows = obj.Where(o => o.Operation == INSERT).Select(s => s.Book).ToList();

                List<Book> updateRows = obj.Where(o => o.Operation == UPDATE).Select(s => s.Book).ToList();

                List<Book> deleteRows = obj.Where(o => o.Operation == DELETE).Select(s => s.Book).ToList();

                result = await _dapperService.SaveBooks(insertRows, updateRows, deleteRows);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
         

            return result ? StatusCode(200) : StatusCode(500);
        }
    }
}

Controllers/HomeController.cs
using Dapper;
using DapperTuts.Models;
using DapperTuts.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DapperTuts.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IDapperService _dapperService;


        public HomeController(ILogger<HomeController> logger,
            IDapperService dapperService)
        {
            _logger = logger;
            _dapperService = dapperService;
        }

        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            Book book;
            if (id != null)
            {
                
                book = await _dapperService.GetById(id);
            }
            else
            {
                book = new();
            }
            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(Book book)
        {
            if (ModelState.IsValid)
            {
                //Update
                if (book.Id != 0)
                {
                    
                    bool done = await _dapperService.UpdateBook(book);
                    return done ? RedirectToAction(nameof(Index)) : View(book);
                }

                bool success = await _dapperService.AddBook(book);
                if (success)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            ModelState.AddModelError("error", "Invalid Input");
            return View(book);
        }

        public async Task<IActionResult> DeleteBook([FromRoute] int Id)
        {
            bool rowsAffected = await _dapperService.DeleteBook(Id);

            if (rowsAffected)
            {
                return RedirectToAction(nameof(Index));
            }
            return BadRequest("sorry");
        }

        [HttpPost]
        public async Task<IActionResult> GetByName([FromForm] string bookName)
        {
            IEnumerable<Book> books = await _dapperService.GetByName(bookName);

            return View("Index", books);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Book> books = await _dapperService.GetAll();

            return View(books);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/BulkCrud/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "SPA CRUD";
}

<h4 class="text-center">
    SPA - CRUD
</h4>

<div class="app-root">
    <!--Upsert Form-->
    <div class="userInputArea">
        <form>
            <div class="form-group">
                <label for="bookId" class="col-form-label">Book ID : </label>
                <input disabled id="bookId" type="number" class="form-control" />
            </div>

            <div class="form-group">
                <label for="bookName" class="col-form-label">Book Name : </label>
                <input id="bookName" class="form-control" />
            </div>

            <div class="form-group">
                <label for="authorName" class="col-form-label">Author Name : </label>
                <input id="authorName" class="form-control" />
            </div>

            <div class="form-group">
                <label for="isbn" class="col-form-label">ISBN : </label>
                <input id="isbn" class="form-control" />
            </div>

            <input type="button" id="upsertBtn" class="btn btn-success" value="ADD">
            <input type="button" id="cancelUpdate" class="btn btn-danger" value="Cancel Update" style="display:none;">
            <input type="button" id="saveToDbBtn" class="btn btn-primary" value="Save To Database">
        </form>
    </div>

    <!--Data Table-->
    <div class="dataTable table-responsive-sm">

        <table id="myBooks" class="table table-sm table-hover table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <!--<th>ID</th>-->
                    <th>Book Name</th>
                    <th>Author Name</th>
                    <th>ISBN</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in Model)
                {
                    <tr id="bookId_@book.Id">
                        @*<td>
                    @book.Id
                </td>*@
                        <td>
                            @book.BookName
                        </td>
                        <td>
                            @book.AuthorName
                        </td>
                        <td>
                            @book.ISBN
                        </td>
                        <td class="action-flex">
                            <i onclick="UpdateBook(this.parentElement.parentElement,@book.Id,'@book.BookName','@book.AuthorName','@book.ISBN')" class="fas fa-edit"></i>
                            <i onclick="deleteBook(this.parentElement.parentElement)" class="trash-icon fas fa-trash-alt"></i>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!--AJAX Loader-->
<div class="modal-loader"></div>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/index.js" defer></script>
}

Views/Home/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="display-4 text-center">Welcome</h1>

    <div class="row">
        <div class="col-lg-9">
            <h4>Author Name - Book Name - ISBN</h4>
            <ul class="list-group w-50 text-white">
                @foreach (var item in Model)
                {
                    <li class="list-group-item bg-primary">
                        @item.AuthorName - @item.BookName - <a asp-action="DeleteBook" asp-route-Id="@item.Id" class="fas fa-trash-alt trash-icon"></a> -
                        <a asp-controller="Home" asp-action="Upsert" asp-route-id="@item.Id" class="fas fa-edit update-icon"></a>
                    </li>
                }
            </ul>
        </div>

        <div class="col-3 text-left">
            <form asp-controller="Home" asp-action="GetByName" method="post">
                <label for="bookName">Enter Book Name</label>
                <input name="bookName" class="form-group" type="text" id="bookName" />
                <input type="submit" class="btn btn-primary" value="Get Result" />
            </form>
        </div>
    </div>

</div>

Views/Home/Upsert.cshtml
@model Book

@{
    ViewData["Title"] = "Add a Book";
}

<form method="post" class="w-50" asp-controller="Home" asp-action="Upsert">
    <input type="hidden" value="@Model.Id" />

    <div class="form-group">
        <label asp-for="@Model.BookName" class="col-form-label"></label>
        <input asp-for="@Model.BookName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="@Model.AuthorName" class="col-form-label"></label>
        <input asp-for="@Model.AuthorName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="@Model.ISBN" class="col-form-label"></label>
        <input asp-for="@Model.ISBN" class="form-control" />
    </div>

    @if (Model.Id != 0)
    {
        <input type="submit" value="Update" class="btn btn-primary" />
    }
    else
    {
        <input type= "submit" value ="Add" class="btn btn-success" />
    }

    <input type="button" asp-controller="Home" asp-action="Index" value="Back To List" class="btn btn-info" />
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DapperTuts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.0.3/sweetalert2.min.css" integrity="sha512-8dmpOO9N+AXGER3oYs72PYquSb3i0EQ5v3b00HbT1z+v2fKUg1tNADAuWDa3NgoAL1UUQjQFAo9bk5OrJFMG+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.0.3/sweetalert2.min.js" integrity="sha512-se7rAeKOfZFegS0CLG8tfRFy/6eo6onjYPtN/EQlKln72vtgjqW45b+F+HDzJNFPjUF+jaPWuMXYPaMdC6Igrg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DapperTuts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Upsert">Add a Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BulkCrud" asp-action="Index">SPA CRUD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BulkCrud" asp-action="Index">Rollback To Database</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DapperTuts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>